export type ObjectType = 'cube' | 'sphere' | 'cylinder' | 'cone' | 'torus' | 'model' | 'image';

export type MediaFileType = 'video' | 'image';

export interface MediaFileInfo {
  name: string;
  path: string;
  type: MediaFileType;
  extension: string;
}

export type WallSide = 'left' | 'right' | 'floor' | 'ceiling';

export type NavigationMode = 'normal' | 'canvas' | 'decorating';

export type WallTextureType = 'default' | 'metal' | 'stucco' | 'wood' | 'glass' | 'brick' | 'concrete';

export type LightFixtureStyle = 'linear' | 'panel' | 'pendant' | 'spot' | 'industrial';

export type CanvasItemType = 'image' | 'text' | 'rich-text' | 'directory' | 'hyperlink' | 'app-shortcut' | 'file-shortcut' | 'drawing';

export type DrawingStyle = 'pen' | 'marker' | 'spray' | 'highlighter' | 'eraser';

export interface Vector3 {
  x: number;
  y: number;
  z: number;
}

// --- Tunnel topology types ---

export interface IntersectionStyle {
  chamberRadius?: number;
  color?: string;
  decoration?: 'arch' | 'dome' | 'split' | 'custom';
}

export interface TunnelNode {
  id: string;
  position: Vector3;
  label?: string;
  style?: IntersectionStyle;
}

export interface TunnelEdge {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  controlPoints: Vector3[];  // CatmullRomCurve3 control points (min 2 = straight)
  length: number;            // cached arc length in meters
  width?: number;            // default TUNNEL_WIDTH
  height?: number;           // default TUNNEL_HEIGHT
}

export interface TunnelCoordinate {
  edgeId: string;
  t: number;  // 0..1 along edge spline
}

export interface TunnelTopology {
  nodes: TunnelNode[];
  edges: TunnelEdge[];
  rootEdgeId: string;
}

// --- Scene object types ---

export interface SceneObject {
  id: string;
  type: ObjectType;
  name: string;
  position: Vector3;
  rotation: Vector3;
  scale: Vector3;
  color: string;
  directoryPath: string | null;
  modelPath?: string;
  imagePath?: string;
  fontSize?: number;
}

export interface HighwaySign {
  id: string;
  name: string;
  position: Vector3;
  wall: WallSide;
  depth: number; // Z depth in meters
  isAutoGenerated: boolean;
  fontSize?: number;
  edgeId?: string;
}

export interface DateMarker {
  id: string;
  date: string;           // ISO date string
  showTime: boolean;
  position: Vector3;
  wall: WallSide;
  depth: number;          // Z depth in meters
  fontSize?: number;
  edgeId?: string;
}

export interface CeilingLight {
  id: string;
  position: Vector3;
  depth: number;
  brightness: number;
  temperature: number; // 2000K (warm) to 10000K (cool)
  isAutoGenerated: boolean;
  fixtureStyle?: LightFixtureStyle;
  fixtureLength?: number; // meters (default: 3)
  color?: string; // Hex color that overrides temperature
  edgeId?: string;
}

export interface WallSettings {
  color: string;
  brightness: number;
  opacity: number;
  wallpaperPath?: string;
}

export interface WallSection {
  id: string;
  wall: WallSide;
  zStart: number;           // Depth start (e.g., 0, 10, 20...)
  zEnd: number;             // zStart + 10
  color?: string;           // Override color
  texture?: WallTextureType;
  brightness?: number;
  edgeId?: string;
}

export interface DrawingPoint {
  x: number;
  y: number;
  pressure?: number;
}

export interface DrawingStroke {
  points: DrawingPoint[];
  color: string;
  size: number;
  style: DrawingStyle;
}

export interface CanvasItem {
  id: string;
  type: CanvasItemType;
  wall: WallSide;
  sectionId: string;
  position: { x: number; y: number };  // 2D wall coords
  size: { width: number; height: number };
  zIndex: number;
  edgeId?: string;
}

export interface CanvasImageItem extends CanvasItem {
  type: 'image';
  imagePath: string;
}

export interface CanvasTextItem extends CanvasItem {
  type: 'text';
  content: string;
  fontSize: number;
  fontColor: string;
}

export interface CanvasRichTextItem extends CanvasItem {
  type: 'rich-text';
  content: string;
  fontSize: number;
  fontColor: string;
  bold: boolean;
  italic: boolean;
  alignment: 'left' | 'center' | 'right';
  backgroundColor?: string;
}

export interface CanvasDirectoryItem extends CanvasItem {
  type: 'directory';
  directoryPath: string;
  label: string;
}

export interface CanvasHyperlinkItem extends CanvasItem {
  type: 'hyperlink';
  url: string;
  label: string;
}

export interface CanvasAppShortcutItem extends CanvasItem {
  type: 'app-shortcut';
  appPath: string;
  label: string;
  iconDataUrl?: string;
}

export interface CanvasFileShortcutItem extends CanvasItem {
  type: 'file-shortcut';
  filePath: string;
  label: string;
  iconDataUrl?: string;
}

export interface CanvasDrawingItem extends CanvasItem {
  type: 'drawing';
  strokes: DrawingStroke[];
}

export type AnyCanvasItem =
  | CanvasImageItem
  | CanvasTextItem
  | CanvasRichTextItem
  | CanvasDirectoryItem
  | CanvasHyperlinkItem
  | CanvasAppShortcutItem
  | CanvasFileShortcutItem
  | CanvasDrawingItem;

export interface WallImage {
  id: string;
  wall: WallSide;
  imagePath: string;
  zPosition: number; // Fixed Z position where the image is placed
  edgeId?: string;
}

export interface MaterialSettings {
  wallMetalness: number;
  wallRoughness: number;
  floorMetalness: number;
  floorRoughness: number;
  ceilingMetalness: number;
  ceilingRoughness: number;
  wireframeOpacity: number;
  trimOpacity: number;
}

export interface NeuralPulseSettings {
  pulseColor: string;
  baseGlow: number;
  ambientSpeed: number;
  ambientIntensity: number;
  reactiveSpeed: number;
  reactiveIntensity: number;
  reactiveSensitivity: number;
}

export interface AtmosphereSettings {
  backgroundColor: string;
  fogColor: string;
}

export interface LightingColors {
  accentColor: string;
  secondaryColor: string;
  ambientLightColor: string;
}

export interface SceneSettings {
  lightBrightness: number;
  envBrightness: number;
  drawDistance: number;
  haziness: number;
  navigationSpeed: number;
  walls: {
    left: WallSettings;
    right: WallSettings;
    floor: WallSettings;
    ceiling: WallSettings;
  };
  materials?: MaterialSettings;
  neuralPulse?: NeuralPulseSettings;
  atmosphere?: AtmosphereSettings;
  lightingColors?: LightingColors;
}

export interface SceneState {
  objects: SceneObject[];
  signs: HighwaySign[];
  lights: CeilingLight[];
  wallImages?: WallImage[];
  wallSections?: WallSection[];
  canvasItems?: AnyCanvasItem[];
  dateMarkers?: DateMarker[];
  settings?: SceneSettings;
  tunnelTopology?: TunnelTopology;
  cameraPosition: Vector3;
  cameraTarget: Vector3;
}

export interface IElectronAPI {
  selectDirectory: () => Promise<string | null>;
  openDirectory: (path: string) => Promise<void>;
  selectModelFile: () => Promise<string | null>;
  selectImageFile: () => Promise<string | null>;
  selectFile: () => Promise<string | null>;
  selectApp: () => Promise<string | null>;
  saveState: (state: SceneState) => Promise<void>;
  loadState: () => Promise<SceneState | null>;
  readFile: (path: string) => Promise<ArrayBuffer>;
  openUrl: (url: string) => Promise<void>;
  openPath: (path: string) => Promise<void>;
  getFileIcon: (path: string) => Promise<string>;
  listMediaFiles: (directoryPath: string) => Promise<MediaFileInfo[]>;
}

declare global {
  interface Window {
    electronAPI: IElectronAPI;
  }
}
